### ISSUE TITLE
Storage Class configuration in ibm-object-storage-plugin-2.2.13

### ISSUE THREAD

**Issue by HendrikSchrieber** [IBM/ibmcloud-object-storage-plugin#132]
We updated ibm-object-storage-plugin from version 2.2.12 to 2.2.13 recently without changing any configuration settings of the plugin. After applying the update newly created PVCs threw an 404 error for not beeing able to locate our S3 buckets anymore. It seems version 2.2.13 contains undocumented changes to the way `Ibm Io Object Storage Endpoint` and `Ibm Io Object Storage Class` are set.

In version 2.2.12, regional storage classes (like "ibmc-s3fs-smart-perf-regional") were set to use `https://s3.private.eu-de.cloud-object-storage.appdomain.cloud` as `Ibm Io Object Storage Endpoint` and `eu-de-smart` as `Ibm Io Object Store Storage Class`.
In version 2.2.13, the same storage class is now using `https://s3.private.mil01.cloud-object-storage.appdomain.cloud` as `Ibm Io Object Storage Endpoint` and `mil01-smart` as `Ibm Io Object Store Storage Class`.

What we expected to happen:
A breaking change like this should at least be documented in the change logs (https://cloud.ibm.com/docs/containers?topic=containers-cos_plugin_changelog) and possibly even be reflected in an increase in minor version. Also in IBM terms, a region would be "eu-de" and not "mil01", which is a single datacenter (see https://cloud.ibm.com/docs/cloud-object-storage/basics?topic=cloud-object-storage-endpoints#endpoints-region). Although it might be useful to be able to select a single datacenter endpoint, this should be a new storage class, in my opinion.

**Comment by Bhagyashreek8** [comment]
Hi @Hendrik-LGLN Thank you for raising the issue and bringing it our notice.

Somehow we slipped this upgrade verification in our recent chart release. 

As you mentioned, there are changes wrt regional storageclasses in 2.2.13 charts, upgrade action will fail for the plugin. Users must uninstall the current charts and reinstall v2.2.13.
This change will have minor impact for the customers using single site clusters as the regional storageclasses will now point to singlesite endpoint instead of regional endpoints.  So the existing buckets created with regional endpoints cannot be accessed from single site endpoint.  Users will see below error while trying to create new PVC with existing buckets in 2.2.13 chart.

```
 status code: 404, request id: 6f027f33-fe4c-4576-b8eb-d90ad84d59fd, host id:
  Normal   Provisioning        23s (x12 over 5m15s)  ibm.io/ibmc-s3fs_ibmcloud-object-storage-plugin-6b47474f5b-bxgtc_61ed4300-b1f9-43df-85d7-ffdb2ddcaeb9  External provisioner is provisioning volume for claim "default/regionalpvc"
  Warning  ProvisioningFailed  23s (x3 over 83s)     ibm.io/ibmc-s3fs_ibmcloud-object-storage-plugin-6b47474f5b-bxgtc_61ed4300-b1f9-43df-85d7-ffdb2ddcaeb9  (combined from similar events): failed to provision volume with StorageClass "ibmc-s3fs-smart-perf-regional": regionalpvc : cgi5lj0w0s2a56ua5gc0 :cannot access bucket ambregionalbucket: NotFound: Not Found
           status code: 404, request id: b6c9439d-33c6-4318-8d03-7415c1a47ec1, host id:
```

**Workaround**: In 2.2.13 chart ,User can add annotation: `[ibm.io/endpoint](http://ibm.io/endpoint): <regional-endpoint>` in PVC Spec to use existing bucket (created using regional endpoint in earlier chart versions) to create new PVC.
 **Steps to find the regional endpoint of existing bucket:**
 From IBMCloud UI, select appropriate Cloud Object Storage Instance where your bucket resides. Click on the Bucket from the list and navigate to Configuration -> Endpoints. Choose an endpoint from the list and add as annotation in PVC Spec.
**NOTE**:
1. Existing buckets with existing workloads will work seamlessly with no impact.
2. In any case, there is no data loss for users.

Chnagelog will be updated asap.


Thank you.

**Comment by HendrikSchrieber** [comment]
Thanks, works for me!
